# VIA_ENABLE = yes
LTO_ENABLE = yes
COMBO_ENABLE = no
AUDIO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes

DEBOUNCE_TYPE = asym_eager_defer_pk
# DEBOUNCE_TYPE = sym_eager_pk

TAP_DANCE_ENABLE = no
RGBLIGHT_ENABLE = no
